.TH OLED 8 "Dec 2019" "Oracle Linux Enhanced Diagnostics" "0.1"

.SH NAME
oled - Interface to invoke other diagnostic tools

.SH SYNOPSIS
oled [sub_command] [options]

.SH DESCRIPTION
OLED (Oracle Linux Enhanced Diagnostics) is a collection of diagnostic tools
and scripts. The \fBoled\fR command is used to invoke these other tools/scripts.
See usage below, for available options.

.TP
# oled help
Oracle Linux Enhanced Diagnostic Tools

Usage:
  /usr/sbin/oled <sub_command> <command_options>

Valid sub-commands:
     smtool          -- Security mitigation tool
     lkce            -- Linux Kernel Core Extractor
     memstate        -- Capture and analyze memory usage statistics
     memtracker      -- Capture memory usage data for offline debug
     filecache       -- List the biggest files in page cache
     dentrycache     -- List a sample of active dentries
     kstack          -- Gather kernel stack based on the process status or PID
     topstack        -- Gather kernel stack and more based on the CPU utilization
     help            -- Show this help message
     version         -- Print version information

Please check the man page of each sub-command to learn more about that tool and
its usage.

.SH EXAMPLES
.TP

# oled memtracker -h
usage: memtracker [-h] [interval]

Log memory usage data continuously.

positional arguments:
  interval    delay, in seconds, between samples (default is 30s)

optional arguments:
  -h, --help  show this help message and exit

.SH REPORTING BUGS
.TP
Please contact Oracle Linux Support to report any bugs for OLED tools.
