.TH oled 8 "Dec 2019" "0.1"

.SH NAME
oled - Program to invoke other diagnostic tools

.SH SYNOPSIS
oled [options]

.SH DESCRIPTION
oled program is used to invoke other diagnostic tools of oled-tool package.

Ex: oled can be used to invoke smtool, lkce, kstack, etc

.TP
# oled help
Oracle Linux Enhanced Diagnostic Tools

Usage:
  /usr/sbin/oled <command> <subcommand>

Valid commands
     smtool      -- security mitigation tool
     memstate    -- captures and analyzes memory usage data
     memtracker  -- captures memory usage data
     lkce        -- Linux Kernel Core Extractor
     kdump       -- configure oled related kdump options
     kstack      -- gathers kernel stack based on the process status or PID
     help        -- show this help message
     version     -- show oled-tools version

.SH OPTIONS
.TP
smtool - run security mitigation tool

.TP
memstate - captures and analyzes memory usage data

.TP
memtracker - captures memory usage data

.TP
lkce - run Linux Kernel Core Extractor

.TP
kdump - configure oled related kdump options

.TP
kstack - gathers kernel stack based on the process status or PID

.SH EXAMPLES
.TP

# oled lkce
Usage: /usr/lib/oled-tools/lkce <options>
options:
        enable          -- enable lkce
        disable         -- disable lkce
        configure [--default]   -- configure lkce
        configure [--show]      -- show lkce configuration
        status          -- print status of lkce
        clean [--all]   -- clear old crash*out files
        list            -- list crash*out files


.SH AUTHOR
.TP
Manjunath Patil <manjunath.b.patil@oracle.com>
