.TH OLED SMTOOL 8 "Jan 2020" "Oracle Linux Enhanced Diagnostics" "0.1"

.SH NAME
oled smtool - Scans, reports and mitigates various known vulnerabilities
on the system.

.SH SYNOPSIS
oled smtool [-h] [-v] [-s] [--enable-default-mitigations [-y] [-d]]
[--enable-full-mitigations [-y] [-r] [-d]]
[--disable-mitigations [-y] [-r] [-d]]

.SH DESCRIPTION
smtool can be used to scan for various known vulnerabilities on the system
and report the mitigation status. The tool also checks if the kernel/microcode
version supports mitigation for all vulnerabilities and provides appropriate
recommendations.

It also allows the user to enable/disable mitigations for
various vulnerabilities both at boot time and runtime.

.SH OPTIONS
.TP
-h, --help
    Displays various options that can be used with the
smtool command.

.TP
-s, --scan
    Scans the mitigation status of various vulnerabilities
and recommends upgrades to kernel/microcode versions, if any.

.TP
-v, --verbose
    Similar to scan but provides more details about
the mitigation status.

.TP
--enable-default-mitigation [-y] [-d]
    Option to reset or enable
default mitigations for various known vulnerabilities. If "-y" or
"--yes" is used in conjunction with this option, it alters the
grub file without prompting the user for confirmation. System
will require a reboot to enable changes made by this option.

If the option "-d" or "--dry-run" is used with this option,
then the vulnerabilities for which the mitigation will
be enabled. It also recommends upgrades to kernel/microcode
versions, if any.

.TP
--enable-full-mitigation [-y] [-r] [-d]
    Option to enable full
mitigations for various known vulnerabilities. If "-y" or
"--yes" is used in conjunction with this option, it alters the
grub file without prompting the user for confirmation. System
will require a reboot to enable changes made by this option.

If option -r or --runtime is used in conjunction with this
option, the tool allows the user to enable mitigations in
runtime.

If the option "-d" or "--dry-run" is used with this option,
then the vulnerabilities for which the mitigation will
be enabled. It also recommends upgrades to kernel/microcode
versions, if any.

.TP
--disable-mitigations [-y] [-r] [-d]
    Option to disable
mitigations for various known vulnerabilities. If "-y" or
"--yes" is used in conjunction with this option, it alters the
grub file without prompting the user for confirmation. System
will require a reboot to enable changes made by this option.

If option -r or --runtime is used in conjunction with this
option, the tool allows the user to disable mitigations in
runtime.

If the option "-d" or "--dry-run" is used with this option,
then the vulnerabilities for which the mitigation will
be enabled. It also recommends upgrades to kernel/microcode
versions, if any.

.SH MISC
.TP
The tool supports the following platforms: KVM_GUEST, KVM_HOST, Bare Metal,
Xen Guest, and Xen Hypervisor. It supports UEK and RHCK kernels but has been
minimally validated for UEK2, UEK3 and RHCK kernels.

.SH REPORTING BUGS
.TP
Please contact Oracle Linux Support to report any bugs for OLED tools.
