.TH GATHER 8
.SH NAME
oled gather \- Collect the basic data needed when filing bugs.
.SH SYNOPSIS
\fB oled gather
\fB-d\fR|\fB-r\fR
[\fB\-h\fR]
[\fB\-y\fR]
[\fB\-v\fR]
[\fB\-t\fI DIR \fR]
[\fB\-w\fI DATE \fR]
.SH DESCRIPTION
\fBgather\fR is used to collect the data needed to troubleshoot the majority of OS issues on standard Exadata Cloud systems.  This includes, core file, sosreport, and Exawatcher files.
.SH OPTIONS
.TP
\fB\-d\fR,\fB--dryrun\fR
Run in dryrun mode.
.TP
\fB\-r\fR,\fB--run\fR
Run the \fBgather\fR command.
.TP
\fB\-h\fR,\fB--help\fR
Display help message.
.TP
\fB\-y\fR,\fB--yes\fR
Answer yes when prompted.
.TP
\fB\-v\fR,\fB--verbose\fR
Toggle verbose output.
.TP
\fB\-t\fI DIR\fR,\fB--target\fI DIR\fR
Specify the target directory(\fIDIR\fR) for output files.  By default \fBgather\fR will pick a local filesystem with the most space available.
.TP
\fB\-w\fI DATE\fR,\fB--when\fI DATE\fR
Specify the date of the problem.
Format is \fIYYYY_MM_DD\fR.  Defaults to today's date.
.SH ASSUMPTIONS
This first version is written specifically for Exadata Cloud systems.  Corefile directories will be in /u01/crashfiles or /crashfiles.  Exawatcher files are in in /opt/oracle.Exawatcher/archive.
.SH FILES
.TP
\fI/tmp/gather.log\fR
The log file containing all the detailed information from the latest run.
